language: node_js
node_js:
  - node
  - io.js
  - 5.5
  - 4.2
  - 4.1
  - 0.12
  - 0.10
sudo: false
services:
  - redis-server

script: "npm run test-coverage && karma start --single-run"

after_script: "npm run coverage && cat ./coverage/lcov.info | coveralls"
