import $ from 'jquery';
import _ from 'lodash';
import bootstrap from 'bootstrap';
import angular from 'angular';
import uirouter from 'angular-ui-router';
import AdminLTE from 'almasaeed2010/AdminLTE/dist/js/app';
import 'angular/bower-angular-cookies';
import 'eu81273/angular.snackbar';
import 'moment';
import 'urish/angular-moment';
